version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hack-knight-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - hack-knight-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hack-knight-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - hack-knight-network

networks:
  hack-knight-network:
    driver: bridge

